### ISSUE TITLE
Add in-class work to hub-feb-14

### ISSUE THREAD

**Issue by dhensby** [timruffles/backbone-class#4]
Thanks a bunch for the talk on Friday, was great to get up to speed.

Could you please push the rest of the work you did during the class? I'm especially interested in seeing how one can use  a `pubSub` object to coordinate multiple / nested views.

Thanks!

**Comment by timruffles** [comment]
Thanks for coming along!

All work up now. I've previously [written up](http://blog.safaribooksonline.com/2013/10/02/decoupling-backbone-applications-with-pubsub/) the pubSub pattern.

**Comment by dhensby** [comment]
Great stuff, thanks
